# Generated by Django 3.1.3 on 2021-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'Student')], null=True),
        ),
    ]
